#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Update Checker

env:
  REPOS: |
    https://github.com/coolsnowwolf/lede master 01
    https://github.com/xiaorouji/openwrt-passwall-packages main 02
    https://github.com/xiaorouji/openwrt-passwall main 03

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */18 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        cd $GITHUB_WORKSPACE
        mkdir -p TMP_SHA
        cd $GITHUB_WORKSPACE/TMP_SHA
        # 将 REPOS 按行拆分并遍历处理
        echo "$REPOS" | while read repo_url repo_branch id; do
          if [ ! -z "$repo_url" ]; then
            echo "Checking $repo_url"
            git clone --depth 1 "$repo_url" -b "$repo_branch" "$id"
            cd "$id"
            commit_hash=$(git rev-parse HEAD)
            echo "SHA_$id=${commit_hash}" >> $GITHUB_OUTPUT
            cd ..
          fi
        done
        cd $GITHUB_WORKSPACE
        rm -rf TMP_SHA

    - name: Show Commit Head and Combination Heads
      id: combHeader
      run: |
        echo "commitHash=\
        ${{steps.getHash.outputs.SHA_01}}\
        ${{steps.getHash.outputs.SHA_02}}\
        ${{steps.getHash.outputs.SHA_03}}" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v4
      with:
        path: .commitHash
        key: HEAD-${{ steps.combHeader.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.combHeader.outputs.commitHash }} | tee .commitHash

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ github.token }}
        event-type: Source Code Update

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
